[package]
name = "cryp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4"
openssl = "0.10"
openssl-sys = "0.9"
hmac = "0.12"
sha2 = "0.10"
pbkdf2 = "0.12"